### ISSUE TITLE
Destroys java lambda expressions

### ISSUE THREAD

**Issue by ukuhnhardt** [jhipster/prettier-java#554] opened 2022-09-27 07:46 UTC
**Prettier-Java 1.6.2**

```sh
# Options (if any):
  "prettier": {
    "tabWidth": 2,
    "semi": false,
    "trailingComma": "es5",
    "singleQuote": true,
    "printWidth": 100
  }
```

**Input:**

```java
// code snippet
  @DELETE
  @Path("/signapprovers/{projectKey}/{repoSlug}")
  @Consumes({ MediaType.APPLICATION_JSON })
  @PermissionRequired({ Permission.REPO_ADMIN })
  public Response deleteSignapprovers(
    @PathParam("projectKey") final String projectKey,
    @PathParam("repoSlug") final String repoSlug,
    RestBranchSignapprovers signapprovers
  ) {
    Repository repository = repositoryService.getBySlug(projectKey, repoSlug);
    RestCommand c = new RestCommand(
      authenticationContext,
      permissionService,
      repository.getProject().getId(),
      repository.getId()
    ) {
      @Override
      Response doExecute() {
                dao.getSignapprovers(projectKey, Optional.of(repoSlug)).ifPresent(l -> { // <<<<<<<<<< OK
                    l.remove(signapprovers);
                    dao.setSignapprovers(projectKey, Optional.of(repoSlug), l);
                    try {
                        auditEventPublisher.publishRepositoryAuditEvent(projectKey, repoSlug, signApproverJsonUtil.serializeNonNull(signapprovers), WorkzoneConfigChangedEvents.WorkzoneSignApproversConfigDeletedEvent.name());
                    } catch (IOException e) {
                        log.warn(e.getMessage(), e);
                    }

                });
        return Response.ok().build();
      }
    };
    return c.execute();
  }
```

**Output:**

```java
// code snippet
 @DELETE
  @Path("/signapprovers/{projectKey}/{repoSlug}")
  @Consumes({ MediaType.APPLICATION_JSON })
  @PermissionRequired({ Permission.REPO_ADMIN })
  public Response deleteSignapprovers(
    @PathParam("projectKey") final String projectKey,
    @PathParam("repoSlug") final String repoSlug,
    RestBranchSignapprovers signapprovers
  ) {
    Repository repository = repositoryService.getBySlug(projectKey, repoSlug);
    RestCommand c = new RestCommand(
      authenticationContext,
      permissionService,
      repository.getProject().getId(),
      repository.getId()
    ) {
      @Override
      Response doExecute() {
        dao
          .getSignapprovers(projectKey, Optional.of(repoSlug))
          .ifPresent(l -> ); /// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<!!!!!!!!!!!!!!!!!!!!!!!!!!! GONE !!!!!!!!!!!!!!!!!!!!!!!
        return Response.ok().build();
      }
    };
    return c.execute();
  }

```

**Expected behavior:**
Don't swallow the lambda expression.

**Comment by clementdessoude** [comment] 2022-09-27 09:08
Hi @ukuhnhardt ! I tried to reproduce, but was not able to. I created a small repo to try to reproduce here: https://github.com/clementdessoude/prettier-java-demo

And here is the output I got:

<img width="715" alt="Screen Shot 2022-09-27 at 11 05 00" src="https://user-images.githubusercontent.com/25530077/192484315-45576ff2-c97b-4352-9f3f-d186890ecee5.png">

As I cannot reproduce, I will close the issue but feel free to comment, and I will reopen it :)

**Closed by clementdessoude** 2022-09-27 09:08 UTC

**Comment by ukuhnhardt** [comment] 2022-09-29 12:46
Thanks for the quick reply! The problem on my side was an older version of prettier (1.18.2). Once I upgraded to the same version as the test repo it works fine.
Thanks again for the great work and apologies for the trouble! Cheers, Ulrich
