### ISSUE TITLE
Issues with v.2.6.1

### ISSUE THREAD

**Issue by DennisRippinger** [jhipster/prettier-java#676] opened 2024-07-12 07:11 UTC
With the update to 2.6.1 the setup no longer works. I created a minimal project setup:

package-info.json
```json
{
  "devDependencies": {
    "prettier": "3.3.2",
    "prettier-plugin-java": "^2.6.1"
  }
}
```

Results in 

```bash
 npm --version
10.8.1

npx prettier --write "**/*.java"
[error] Cannot find module '/Users/dennis/prettier-test/node_modules/prettier-plugin-java/src/index.js' imported from /Users/dennis/prettier-test/node_modules/prettier/index.mjs
```

Same result with the prettier version 3.2.5.

**Comment by jtkiesel** [comment] 2024-07-12 08:29
Well, I sure screwed up my first release of this project. I'll be working to update the documentation for (and hopefully better automate the process of) releasing this project. `prettier-plugin-java@2.6.4` is now published and appears to be working, so please try that version at your earliest convenience.

I am terribly sorry to you and anyone else that was inconvenienced by this mistake. I have deprecated versions `2.6.1`, `2.6.2`, and `2.6.3` with a message instructing that those versions are broken and to update to `>=2.6.4`.

**Comment by reitzig** [comment] 2024-07-12 10:35
Apparently there were breaking changes, too; the PR bumping from 2.6.0 to 2.6.4 reports

```
[warn] Code style issues found in 2 files. Run Prettier with --write to fix.
```

The diff, if that helps any:
![image](https://github.com/user-attachments/assets/e0026cec-5410-4ee0-b3d7-1bbb30709234)

Sure enough, the format changed.

**Comment by jtkiesel** [comment] 2024-07-12 14:25
@reitzig You bring up very good points. I hadn't fully considered what SemVer might mean for a code formatter, and so for this release focused on the fact that since 2.6.0 had a regression, I should release a bug fix for it. In hindsight, I may need to do some research & thinking about how to treat SemVer in this project, as like you pointed out, a code formatter might need a different interpretation, but I also don't know that my current interpretation is correct. Closing this issue as resolved now, but I'm happy for input/feedback on that, while I consider our options.

**Closed by jtkiesel** 2024-07-12 14:25 UTC

**Comment by jhaber** [comment] 2024-07-12 14:31
I believe pretty much every release includes formatting changes, kind of by definition, so I would expect a breaking change to apply more to usage of the tool, rather than the formatting output. For example, prettier itself is on v3, and they've also introduced formatting changes with every release. However they did a major version bump from v2 -> v3 when changing the API of the formatter library itself
