### ISSUE TITLE
How do specify plugins without requiring a fully qualified path?

### ISSUE THREAD

**Issue by larsks** [jhipster/prettier-java#639] opened 2024-01-19 16:00 UTC
I have installed `prettier` and `prettier-plugin-java` globally:

```
$ npm -g list
/home/larsks/lib/npm-packages/lib
├── prettier-plugin-java@2.5.0
└── prettier@3.2.4
```

Attempting to format some Java code like this failed:

```
$ prettier Example.java
[error] Cannot find package 'prettier-plugin-java' imported from /home/larsks/tmp/java/noop.js
```

That's unpleasant but perhaps expected based on #508. But this also fails:

```
$ prettier --plugin prettier-plugin-java Tile.java
[error] Cannot find package 'prettier-plugin-java' imported from /home/larsks/tmp/java/noop.js
```

The only thing that worked was this:

```
$ prettier --plugin ~/lib/npm-packages/lib/node_modules/prettier-plugin-java/dist/index.js Tile.java
[error] Cannot find package 'prettier-plugin-java' imported from /home/larsks/tmp/java/noop.js
```

And...that's a lot of typing. I would put that into `.prettierrc.yaml`, but neither `~` nor `$HOME` work in that file to refer to my home directory, which means that I can't suggest this to colleagues as a generic solution, and if I happen to have different home directories in different environments (which I do) I can't use the same configuration file (and I can't make `.prettierrc` part of a project repository, because it would need to be modified by everybody in their own working directory).

Is there any way to make this work in a more graceful fashion?

**Comment by jtkiesel** [comment] 2024-01-19 16:03
This appears to be identical to #630. See my response there for a temporary workaround.

**Comment by jtkiesel** [comment] 2024-06-12 02:58
Closing as duplicate of #630.

**Closed by jtkiesel** 2024-06-12 02:58 UTC
