### ISSUE TITLE
Use different indentation level for `throws`

### ISSUE THREAD

**Issue by jsh9** [jhipster/prettier-java#583] opened 2023-06-21 04:34 UTC
I tried Prettier-java today and saw this formatting result:

```java
public void myMethodWithLongName(final boolean myArg1, ...)
    throws IOException {
    final String myVariable = "123";
    ...
```

This makes the `throws` line and the 1st line of the method body visually indistinguishable.  Is it possible to change this behavior?

I think a potential solution would be: to allow a different indentation level (such as 8) for line break indentations.

**Comment by jhaber** [comment] 2023-07-11 13:14
I believe this is referred to as a "continuation" indent. Some related discussion: 
https://github.com/jhipster/prettier-java/issues/429
https://github.com/jhipster/prettier-java/pull/384#discussion_r410712022

**Comment by jtkiesel** [comment] 2024-07-14 04:18
Closing as a duplicate of #429.

**Closed by jtkiesel** 2024-07-14 04:18 UTC
